[PB-557] bug: file size from the drive-server comes as string
internxt/drive-server pull request #417
Opened 2023-09-21 01:09 UTC by edisonjpadilla

2023-09-21 09:54 UTC, JoanVicens reviewed
Tested and works, but why do we parser to a float?  The size is in bytes so it shuld be always an integer


![imatge](https://github.com/internxt/drive-server/assets/38570230/c633ec8d-db35-4912-ae0e-a74befa955fb)

2023-09-21 12:25 UTC, edisonjpadilla commented
@JoanVicens I thought the size was measured in mb.

2023-09-21 13:17 UTC, JoanVicens approved these changes

2023-09-21 13:37 UTC, JoanVicens commented
@PixoDev Can this break anything on mac?

2023-09-21 13:50 UTC, PixoDev commented
This will break a lot of API responses in the MacOS app because we are expecting an string there @JoanVicens @edisonjpadilla.

Let me think a solution for this so we don't break production already please, don't merge this yet

2023-09-21 14:00 UTC, JoanVicens requested changes
Added a new review to block the merge button. We need to ensure this will not break any client

2023-09-21 14:02 UTC, JoanVicens commented
We could add a new field so the clients can migrate to it and once every client no longer uses it change the size to number (and migrate again?) @sg-gs

2024-05-30 13:46 UTC, jzunigax2 commented
> We could add a new field so the clients can migrate to it and once every client no longer uses it change the size to number (and migrate again?) @sg-gs

@JoanVicens I was taking a look into this old issue, is this approach still needed?

2024-05-30 14:24 UTC, JoanVicens commented
> > We could add a new field so the clients can migrate to it and once every client no longer uses it change the size to number (and migrate again?) @sg-gs
> 
> @JoanVicens I was taking a look into this old issue, is this approach still needed?

Yes, I believe that the parsing of the JSON on the Mac application relies on the type of the fields being what they expect, so changing the size to a number would be a breaking change.

2024-06-12 15:47 UTC, JoanVicens approved these changes

2024-06-12 20:00 UTC, apsantiso commented
This solution is the way to go if we aim for non breaking changes, but it introduces technical debt. Specifically, you would need to replicate this approach in the `drive-server-wip` repository (you could add it to the domain layer instead of using a virtual value). Moreover, if we decide to change the size to numeric, the client currently using this virtual value would need to switch back to using size.

This issue originates from Sequelize, where the `size` ( in the DB ) column is of type "bigint". Sequelize cannot ensure that very large numbers are safely parsed to `Number`, so it parses this column as a `String` for such cases. However, the MAX SAFE INTEGER in JavaScript is close to 8000TB (9007199254740991 in bytes), so we can safely parse this to Number without any problems if needed. 

@sg-gs @jzunigax2 Feel free to merge this, but I believe such issues should be addressed at the root level. Instead of adding more columns, we could have the macOS client handle either strings or numbers if possible.

2024-06-12 20:01 UTC, apsantiso approved these changes

2025-09-30 11:05 UTC, closed without merging